### ISSUE TITLE
Initial release date

### ISSUE THREAD

**Issue by Softtinn** [NumerousTechnology/MdView#1]
Hi!
Looks very interesting! We're currently using the built in HTML support for our formatted texts, but it leaves much to be desired.... Do you have a planned releasedate for the first sharp release? :-)

**Comment by axvr** [comment]
There isn't a release date set, but I'm aiming for a v1.0 release by the end of this month or early January.

**Comment by SailorTurkey** [comment]
Any release date yet?

**Comment by axvr** [comment]
Sorry, been busy lately, hopefully sometime during April.

**Comment by axvr** [comment]
[v0.7 is now available on NuGet.org](https://www.nuget.org/packages/MdView).  I'm still writing documentation \(#6\) but if you want to use it now, you can read the [source code](https://github.com/NumerousTechnology/MdView/tree/master/MdView) and see how it is used in the [sample app source code](https://github.com/NumerousTechnology/MdView/tree/master/MdView.Sample).
